### ISSUE TITLE
Unhandled 'error' event error

### ISSUE THREAD

**Issue by thedamon** [remorses/workspace-dependency-graph#2]
Getting a little error and not sure where it's coming from. I can't figure out where events.js is specifically but doesn't seem to be in my codebase.

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn dot ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn dot',
  path: 'dot',
  spawnargs: [ '-Grankdir=LR', '-Tsvg' ]
}
```

**Comment by thedamon** [comment]
It produced the diagraph thing though, so totally usable

**Comment by jfulse** [comment]
Hello! I got the same issue, but no graph.

**Comment by pete-the-pete** [comment]
I went through https://github.com/vogloblinsky/gulp-angular-architecture-graph/issues/2 and https://github.com/vogloblinsky/gulp-angular-architecture-graph#windows-7, which resolved my issue.
